### ISSUE TITLE
[gen4] should ref be a State?

### ISSUE THREAD

**Issue by kevinresol** [MVCoconut/coconut.ui#29]
So instead of `{current:T}` it is `State<T>`

so in `viewDidMount` we can write:

```haxe
var binding = ref.bind(null, div -> doSomething(div));
untilUnmounted(binding.dissolve);
```

otherwise with the current implementation we need to handle both `viewDidMount` and `viewDidUpdate`? Or did I miss something?

**Comment by back2dos** [comment]
If you want to run something every time the ref changes, the most straight forward way would be to just use a function:

```jsx
<div ref={div -> if (div != null) doSomething(div)} />
```

But if you have other use cases, we could consider it. Personally, I think it's a bit "dangerous" because if the ref is read in the render function, then that will create a loop.

**Comment by kevinresol** [comment]
Okay
