### ISSUE TITLE
Type not found : TagCreate

### ISSUE THREAD

**Issue by Dvergar** [MVCoconut/coconut.ui#38]
When pasting your first sample from the doc it triggers:
`coconut,ui/0,9,0/src/coconut/ui/macros/Generator.hx:63: characters 55-64 : Type not found : TagCreate`

I don't know if there's some magic under the hood but `TagCreate` in `Generator.hx` is imported with `import tink.hxx.Generator.TagCreate;` and doesn't seem to exist in that file (unless built from macro !?).

`TagCreate` exists in `tink.hxx.Generator.Tag` though, but importing it spawn different errors.

_I'm using haxe4-rc1_

**Comment by kevinresol** [comment]
You need to update all dependencies to latest git versions

**Comment by Dvergar** [comment]
Thanks, will do !

**Comment by andyli** [comment]
I got the same error when trying to compile examples-todomvc when using Haxe 3.4.7 and the latest haxelib releases:
```
> haxelib list
coconut.data: [0.8.1]
coconut.ui: [0.9.0]
coconut.vdom: [0.6.2]
js-virtual-dom: [0.12.1]
lessie: [1.1.1]
tink_anon: [0.3.3]
tink_core: [1.21.0]
tink_csss: [0.1.0]
tink_hxx: [0.21.0]
tink_lang: [0.6.2]
tink_macro: [0.17.4]
tink_parse: [0.2.0]
tink_priority: [0.1.4]
tink_pure: [0.4.0]
tink_slice: [0.1.0]
tink_state: [0.10.1]
tink_syntaxhub: [0.4.3]
```

Is it possible to push a new release of something and make the life easier for those who are not on cutting edge? :)

**Comment by kevinresol** [comment]
I just updated the libraries (in `haxe_libraries`, for lix) and it should compile for haxe 3.4.7, 4rc1 and 4rc2.

It is strongly recommended to use lix for the dependency management because there are so many libraries and some of them actually won't work on latest edge (but need a few commits earlier).

If you insist on haxelib, you might need to manually compare the library versions listed in the `haxe_libarires` folder until _all_ the libraries has a proper release.

##### Note on how to use lix:
1. install nodejs
1. run `yarn` or `npm install` in the `examples-todomvc` folder
1. run `yarn haxe todomvc-react.hxml` or `npx haxe todomvc-react.hxml`
