### ISSUE TITLE
[regression] Function type attributes are generated as member function?

### ISSUE THREAD

**Issue by kevinresol** [MVCoconut/coconut.ui#40]
```haxe
import coconut.Ui.hxx;

class Main extends coconut.ui.View {
	
	static function main() {
		trace(hxx('<Main/>'));
	}
	
	@:attr var onPress:Void->Void = null;
	
	function render() '
		<div>
			<if ${onPress == null}>
				<div onclick=${onPress}>Button</div>
			<else>
				No Button
			</if>
		</div>
	';
}
```

Generated this:

```js
Main.prototype = $extend(coconut_ui_View.prototype,{
	onPress: function() {
		(tink_state__$Observable_Observable_$Impl_$.get_value(this.__slots.onPress))();
		return;
	}
	,render: function() {
		var __r = [];
		var __r1 = [];
		if(this.onPress == null) {
			var __ret = { onclick : tink_core__$Callback_Callback_$Impl_$.fromNiladic($bind(this,this.onPress))};
			var __r2 = [];
			__r2.push(coconut_vdom__$Child_Child_$Impl_$.ofText("Button"));
			__r1.push(coconut_vdom__$Child_Child_$Impl_$.element("div",__ret,__r2));
		} else {
			__r1.push(coconut_vdom__$Child_Child_$Impl_$.ofText("No Button"));
		}
		__r.push(coconut_vdom__$Child_Child_$Impl_$.element("div",{ },__r1));
		return __r[0];
	}
	,__initAttributes: function(attributes) {
		var this1 = attributes.onPress;
		this.__slots.onPress.setData(this1 == null ? this.__tink_defaults0.onPress : this1);
	}
});
```

Note that `this.onPress` will never be null because it is referencing the instance method. Also, the app will crash when trying to invoke `onPress`, because `get_value()` of the slot will give `null`.
Looks like a serious regression.

**Comment by back2dos** [comment]
Ok, there's a workaround for now. The main idea was [not to cause rerendering if callbacks change](https://github.com/MVCoconut/coconut.ui/issues/31). 

The null error can easily be avoided. But if we want `someFunctionAttribute == null` to work, that's a different story. We could make it so that one can write `hasSomeFunctionAttribute` instead. Or we burry this optimization

**Comment by back2dos** [comment]
Hmm, I think I like the optimization that's currently disabled and I'm thinking to reenable it in a few cases.

For starters, if the function is optional and has a non-null default, because then we know it'll *never* be `null` so the wrapping is safe.

Beyond that, I would also propose that when the attribute is mandatory and not `Null` it's meaningful to assume that `null` is invalid, especially since passing `null` as attribute in HXX probably doesn't work anyway due to type inference. So for mandatory non-`Null` function attributes, I'm inclined to enable this. We could make an explicit null check and throw an error that states more explicitly what's wrong, e.g. `invalid null passed to onPress attribute of <Main />` or something.

**Comment by kevinresol** [comment]
We can have a try
