### ISSUE TITLE
Passing states into lifecycle functions

### ISSUE THREAD

**Issue by kevinresol** [MVCoconut/coconut.ui#5]
For example:
```haxe
class MyView extends View<{data:Data}> {
  override function afterInit(e) {
    // allow accessing `data` here
  }
}
```

Currently I store `data` into a class member during `render`, which doesn't feel too good.

**Comment by back2dos** [comment]
I see. The problem is that lifecycle hooks come from `Renderable`, not `View`, where there's no notion of data.

It would be trivial to [let the constructor store the `data`](https://github.com/MVCoconut/coconut.ui/blob/master/src/coconut/ui/macros/ViewBuilder.hx#L101) into some field (why not `data` ... or maybe `props` for property based views and `model` for model based views).
