### ISSUE TITLE
CSS handling

### ISSUE THREAD

**Issue by volth** [MVCoconut/coconut.ui#7]
Any ideas about how to handle CSS ?
I mean mainly two issues:
1. state-dependent styles.
2. lexical scoping, so the styles of one component do not affect the others.

You may say that ```style=``` html attribute could be used, but it does not cover all cases.
For example, one may want to have
```
<style>
circle {
  fill: ${props.color};
}
</style>
```
applied to thousands of circles made by ```d3``` within the component.
Applying ```style=``` to each circle is not convenient, applying the CSS globally affects other components, so there should be auto-generated scopes per component instance or something.

It is still a hot topic for React though, with many approaches. https://www.styled-components.com might be the leader over there.

PS. I voluntarily used incorrect ```${```-syntax at there could be disambiguation using ```{}``` both for CSS syntax and string-interpolation, which is another issue

**Comment by back2dos** [comment]
First of all, coconut.ui is not really tied to the notion of CSS. It just so happens that right now the only two renderers there are both use CSS. With `coconut.react` I think things would look much like this (maybe @kevinresol can confirm):

```haxe
class Example extends View<{ important:Bool }> {
  var styles = StyleSheet.create({
    button: { /*...*/ },
    important: { /*...*/ }
  });
  function render() '
    <Button style={[styles.button, if (important) styles.important else null]} />
  ';
}
```

(at least for React Native anyway)

And then for `coconut.vdom` it's a different story. My preferred method is the one in the [TodoMVC example](https://github.com/MVCoconut/examples-todomvc). It is true that you may mistakenly set styles on child components. That assumes that's not your intent (after all, you component may be about providing styles to children). Also, even scoping your CSS does not fully isolate things, as there are still some properties that are inherited (e.g. font-size) or otherwise depend on the parent (e.g. dimensions set in em if font-size is inherited). Mostly, I would advise to just make your selectors specific enough, if you want them to be specific - sorry for the tautology ;)

**Comment by kevinresol** [comment]
Confirm that for React Native. But for React (no "Native"), styles are just specified as plain objects, (no string, no arrays) e.g. 
```js
(<p style={{fontSize: 12}}/>)
```



> applied to thousands of circles made by d3 within the component.

If you want to save some keystrokes in that particular scenario, you may write a custom element: (untested)

```haxe
function redCircle(attr:{}, children) '
  <div {...attr} style="background-color: red">$children</div>
';
```
and use it:

```haxe
function render() '
  <redCircle/>
';
```

**Comment by back2dos** [comment]
Yeah, that's generally a useful "technique", but I don't think you can tell d3 to use that render function ^^

**Comment by kevinresol** [comment]
> but I don't think you can tell d3 to use that render function

yeah, true

**Comment by back2dos** [comment]
Out of scope of coconut. For HTML, [cix](https://github.com/back2dos/cix) is probably the best thing I can offer. Beyond that, the frontend community is full with solutions to the problem ;)
