### ISSUE TITLE
View generic parameters should be accessible from everywhere

### ISSUE THREAD

**Issue by grosmar** [MVCoconut/coconut.ui#8]
Right now the only render function can access the generic parameters in view classes.
For example in lifecycle events they can be essential to be able to access them and make computations, etc.

Also when delegate behavior from hxx to views it's not so convenient sometimes to pass all the parameters and it would be simpler to rely on class properties. I know this approach is not functional, but it should be the developer's choice which way he goes

**Comment by kevinresol** [comment]
View has a member variable named `data` which is what you wanted.

**Comment by back2dos** [comment]
Note though that accessing it at arbitrary points in time may trigger recomputation.

**Comment by kevinresol** [comment]
Could you elaborate on the "may"?

**Comment by grosmar** [comment]
Also the `data` is not available during lifecycle events.

**Comment by kevinresol** [comment]
> Also the data is not available during lifecycle events.

It is available, please use latest commit on git

**Comment by back2dos** [comment]
> Could you elaborate on the "may"?

When data changes, coconut views are marked dirty and recomputation is done once for the render. If you query the data at arbitrary points in time, it may be recomputed before. Because currently all data is collated into one observable, it may also cause a lot of invalidation.

Example:

```haxe
function arbitraryMethod() {
  data.onblurb();//invalidation
  if (data.requiresFoo)//computation
    data.onfoo();//invalidation
  if (data.requiresBar)//computation
    data.onbar();//invalidation
}
```

This is not necessarily expensive. But it's important to be aware of it. The render method actually gets a shallow copy of the data. The downside is that it can become stale, but since that will trigger a rerender, it's not a big issue.

Anyway, don't worry about it too much for now. I have plans for changing this anyway ;)

**Comment by back2dos** [comment]
The aforementioned plans have been implemented ;)
